=== svanifer/WebXMLParser/target/xmlparsing/WEB-INF/classes/Task4xsd.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.epam.training.by/classes"
	xmlns:tns="http://www.epam.training.by/classes" elementFormDefault="qualified">
	<element name="candies">
		<complexType>
			<sequence>
				<element name="candy" type="tns:Candy" maxOccurs="unbounded"
					minOccurs="1" />
			</sequence>
		</complexType>
	</element>
	<complexType name="Candy">
		<sequence>
			<element type="string" name="name" />
			<element type="nonNegativeInteger" name="energy" />
			<element name="ingredients" type="tns:Ingredients" />
			<element name="value">
				<complexType>
					<sequence>
						<element type="nonNegativeInteger" name="proteins" />
						<element type="nonNegativeInteger" name="fats" />
						<element type="nonNegativeInteger" name="carbohydrates" />
					</sequence>
				</complexType>
			</element>
			<element type="string" name="production" />
		</sequence>
		<attribute type="tns:Unique" name="id" use="required" />
		<attribute type="string" name="type" use="required" />
		<attribute type="string" name="filling" use="optional" />
	</complexType>
	<simpleType name="Unique">
		<restriction base="ID">
			<pattern value="([a-zA-Z])[0-9]{2,5}" />
		</restriction>
	</simpleType>
	<complexType name="Ingredients">
		<sequence>
			<element name="water">
				<simpleType>
					<restriction base="nonNegativeInteger">
						<maxInclusive value="1000" />
					</restriction>
				</simpleType>
			</element>
			<element type="nonNegativeInteger" name="sugar" />
			<element type="nonNegativeInteger" name="fructose" />
			<element name="chocolate-type" minOccurs="0">
				<simpleType>
					<restriction base="string">
						<enumeration value="white" />
						<enumeration value="milk" />
						<enumeration value="dark" />
					</restriction>
				</simpleType>
			</element>
			<element type="integer" name="vanilla" />
		</sequence>
	</complexType>
</schema>

=== svanifer/WebXMLParser/target/test-classes/testDataOne.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<candies xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://www.epam.training.by/classes" xsi:schemaLocation="http://www.epam.training.by/classes Task4xsd.xsd">
    <candy id="c1001" type="caramel">
        <name>Barbaris</name>
        <energy>10</energy>
        <ingredients>
            <water>10</water>
            <sugar>50</sugar>
            <fructose>0</fructose>
            <vanilla>10</vanilla>
        </ingredients>
        <value>
            <proteins>3</proteins>
            <fats>0</fats>
            <carbohydrates>15</carbohydrates>
        </value>
        <production>Roshen</production>
    </candy>
</candies>

=== svanifer/WebXMLParser/target/test-classes/testDataThree.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<candies xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://www.epam.training.by/classes" xsi:schemaLocation="http://www.epam.training.by/classes Task4xsd.xsd">
    <candy id="c1004" type="chocolate">
        <name>Aeroflot</name>
        <energy>40</energy>
        <ingredients>
            <water>45</water>
            <sugar>80</sugar>
            <fructose>0</fructose>
            <chocolate-type>dark</chocolate-type>
            <vanilla>15</vanilla>
        </ingredients>
        <value>
            <proteins>20</proteins>
            <fats>5</fats>
            <carbohydrates>50</carbohydrates>
        </value>
        <production>Kommunarka</production>
    </candy>
</candies>

=== svanifer/WebXMLParser/target/xmlparsing/WEB-INF/classes/Task4.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<candies xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://www.epam.training.by/classes" xsi:schemaLocation="http://www.epam.training.by/classes Task4xsd.xsd">
		<candy id="c1001" type="caramel">
			<name>Barbaris</name>
			<energy>10</energy>
			<ingredients>
				<water>10</water>
				<sugar>50</sugar>
				<fructose>0</fructose>
				<vanilla>10</vanilla>
			</ingredients>
			<value>
				<proteins>3</proteins>
				<fats>0</fats>
				<carbohydrates>15</carbohydrates>
			</value>
			<production>Roshen</production>
		</candy>
		<candy id="c1002" type="iris">
			<name>Key</name>
			<energy>15</energy>
			<ingredients>
				<water>200</water>
				<sugar>0</sugar>
				<fructose>50</fructose>
				<vanilla>40</vanilla>
			</ingredients>
			<value>
				<proteins>10</proteins>
				<fats>10</fats>
				<carbohydrates>20</carbohydrates>
			</value>
			<production>Kommunarka</production>
		</candy>
		<candy id="c1003" type="chocolate" filling="nuts">
			<name>Alyonka</name>
			<energy>40</energy>
			<ingredients>
				<water>40</water>
				<sugar>70</sugar>
				<fructose>0</fructose>
				<chocolate-type>milk</chocolate-type>
				<vanilla>40</vanilla>
			</ingredients>
			<value>
				<proteins>20</proteins>
				<fats>10</fats>
				<carbohydrates>40</carbohydrates>
			</value>
			<production>Spartak</production>
		</candy>
		<candy id="c1004" type="chocolate">
			<name>Aeroflot</name>
			<energy>40</energy>
			<ingredients>
				<water>45</water>
				<sugar>80</sugar>
				<fructose>0</fructose>
				<chocolate-type>dark</chocolate-type>
				<vanilla>15</vanilla>
			</ingredients>
			<value>
				<proteins>20</proteins>
				<fats>5</fats>
				<carbohydrates>50</carbohydrates>
			</value>
			<production>Kommunarka</production>
		</candy>
	<candy id="m1004" type="chocolate">
		<name>Belochka</name>
		<energy>40</energy>
		<ingredients>
			<water>45</water>
			<sugar>80</sugar>
			<fructose>0</fructose>
			<chocolate-type>white</chocolate-type>
			<vanilla>15</vanilla>
		</ingredients>
		<value>
			<proteins>20</proteins>
			<fats>5</fats>
			<carbohydrates>50</carbohydrates>
		</value>
		<production>Spartak</production>
	</candy>
	<candy id="d1004" type="chocolate" filling="nougat">
		<name>Chocolapki</name>
		<energy>40</energy>
		<ingredients>
			<water>45</water>
			<sugar>80</sugar>
			<fructose>0</fructose>
			<chocolate-type>dark</chocolate-type>
			<vanilla>15</vanilla>
		</ingredients>
		<value>
			<proteins>20</proteins>
			<fats>5</fats>
			<carbohydrates>50</carbohydrates>
		</value>
		<production>Roshen</production>
	</candy>
	<candy id="q1004" type="chocolate" filling="liquor">
		<name>Stolichnye</name>
		<energy>45</energy>
		<ingredients>
			<water>55</water>
			<sugar>80</sugar>
			<fructose>0</fructose>
			<chocolate-type>dark</chocolate-type>
			<vanilla>15</vanilla>
		</ingredients>
		<value>
			<proteins>20</proteins>
			<fats>5</fats>
			<carbohydrates>50</carbohydrates>
		</value>
		<production>Kommunarka</production>
	</candy>
	<candy id="c2004" type="lollipop">
		<name>Dushes</name>
		<energy>40</energy>
		<ingredients>
			<water>45</water>
			<sugar>80</sugar>
			<fructose>25</fructose>
			<vanilla>15</vanilla>
		</ingredients>
		<value>
			<proteins>10</proteins>
			<fats>5</fats>
			<carbohydrates>55</carbohydrates>
		</value>
		<production>Ivkon</production>
	</candy>
	<candy id="c1014" type="lollipop">
		<name>Bim Bom</name>
		<energy>30</energy>
		<ingredients>
			<water>45</water>
			<sugar>90</sugar>
			<fructose>0</fructose>
			<vanilla>5</vanilla>
		</ingredients>
		<value>
			<proteins>10</proteins>
			<fats>3</fats>
			<carbohydrates>67</carbohydrates>
		</value>
		<production>Roshen</production>
	</candy>
	<candy id="g1004" type="chocolate" filling="nuts">
		<name>Marsian</name>
		<energy>60</energy>
		<ingredients>
			<water>40</water>
			<sugar>60</sugar>
			<fructose>0</fructose>
			<chocolate-type>white</chocolate-type>
			<vanilla>15</vanilla>
		</ingredients>
		<value>
			<proteins>25</proteins>
			<fats>15</fats>
			<carbohydrates>45</carbohydrates>
		</value>
		<production>Roshen</production>
	</candy>
	<candy id="c3004" type="chocolate" filling="cream">
		<name>Mishki</name>
		<energy>41</energy>
		<ingredients>
			<water>40</water>
			<sugar>80</sugar>
			<fructose>15</fructose>
			<chocolate-type>milk</chocolate-type>
			<vanilla>15</vanilla>
		</ingredients>
		<value>
			<proteins>20</proteins>
			<fats>5</fats>
			<carbohydrates>50</carbohydrates>
		</value>
		<production>Spartak</production>
	</candy>
	<candy id="c1104" type="caramel">
		<name>Clivki</name>
		<energy>40</energy>
		<ingredients>
			<water>45</water>
			<sugar>80</sugar>
			<fructose>0</fructose>
			<vanilla>15</vanilla>
		</ingredients>
		<value>
			<proteins>20</proteins>
			<fats>5</fats>
			<carbohydrates>50</carbohydrates>
		</value>
		<production>Spartak</production>
	</candy>
	<candy id="c1114" type="lollipop">
		<name>Vzliotnaia</name>
		<energy>40</energy>
		<ingredients>
			<water>45</water>
			<sugar>80</sugar>
			<fructose>0</fructose>
			<vanilla>15</vanilla>
		</ingredients>
		<value>
			<proteins>20</proteins>
			<fats>5</fats>
			<carbohydrates>50</carbohydrates>
		</value>
		<production>Kommunarka</production>
	</candy>
	<candy id="h1004" type="chocolate">
		<name>Beriozka</name>
		<energy>40</energy>
		<ingredients>
			<water>45</water>
			<sugar>80</sugar>
			<fructose>0</fructose>
			<chocolate-type>milk</chocolate-type>
			<vanilla>15</vanilla>
		</ingredients>
		<value>
			<proteins>20</proteins>
			<fats>5</fats>
			<carbohydrates>50</carbohydrates>
		</value>
		<production>Kommunarka</production>
	</candy>
	<candy id="c1000" type="chocolate">
		<name>Belaruskie</name>
		<energy>40</energy>
		<ingredients>
			<water>40</water>
			<sugar>89</sugar>
			<fructose>0</fructose>
			<chocolate-type>dark</chocolate-type>
			<vanilla>15</vanilla>
		</ingredients>
		<value>
			<proteins>27</proteins>
			<fats>15</fats>
			<carbohydrates>70</carbohydrates>
		</value>
		<production>Kommunarka</production>
	</candy>
	<candy id="k1004" type="chocolate" filling="nuts">
		<name>Prometey</name>
		<energy>60</energy>
		<ingredients>
			<water>45</water>
			<sugar>40</sugar>
			<fructose>0</fructose>
			<chocolate-type>milk</chocolate-type>
			<vanilla>15</vanilla>
		</ingredients>
		<value>
			<proteins>22</proteins>
			<fats>25</fats>
			<carbohydrates>40</carbohydrates>
		</value>
		<production>Kommunarka</production>
	</candy>
	</candies>

=== svanifer/WebXMLParser/target/test-classes/testDataTwo.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<candies xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://www.epam.training.by/classes" xsi:schemaLocation="http://www.epam.training.by/classes Task4xsd.xsd">
    <candy id="c1003" type="chocolate" filling="nuts">
        <name>Alyonka</name>
        <energy>40</energy>
        <ingredients>
            <water>40</water>
            <sugar>70</sugar>
            <fructose>0</fructose>
            <chocolate-type>milk</chocolate-type>
            <vanilla>40</vanilla>
        </ingredients>
        <value>
            <proteins>20</proteins>
            <fats>10</fats>
            <carbohydrates>40</carbohydrates>
        </value>
        <production>Spartak</production>
    </candy>
</candies>
